baseurl: "/"
title: "Digital Sovereignty"
author: "Ryan Heywood"
copyright: "Copyright 2020 Ryan Heywood"
paginate: 10
theme: flax

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: false

params:
  # TODO make theme use primaryColor and accentColor
  primaryColor: "#A60006"
  accentColor: "#00a6a0"
  color: "#A60006"
  width: 1440px
  author: Ryan Heywood
  description: Cypherpunk chat protocol nerd.
  footer: >-
    Except where otherwise noted, content on this site is licensed under a &#32;
    <a href="http://creativecommons.org/licenses/by-nd/4.0/" rel="license">
    Creative Commons Attribution No-Derivatives 4.0 International License</a>.
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
  summaries: true
  divider: false
  schema: false         # Set to true to add Schema.org metadata
  opengraph: false      # Set to true to add Open Graph metadata
  twittercards: true    # Set to true to add Twitter Cards metadata

  sidebar:
    blocks:
    - name
    - description
    - about
    - featured_posts
    - recent_posts
    # taxonomies
    # ::TODO:: ^

menu:
  nav:
  - name: About
    url: about/
    weight: 1
  - name: Posts
    url: post/
    weight: 2
# - name: Tags
#   url: tags/
#   weight: 3
# - name: Categories
#   url: categories/
#   weight: 4
  - name: RSS
    url: index.xml
    weight: 5
